### PR TITLE
fix the full page screen capture feature

### PR DESCRIPTION
**Pull request by paine1690**
fix the full page screen capture feature in [issues #24](https://github.com/webfolderio/cdp4j/issues/24)

### CODE REVIEW

**Comment by webfolderio** [comment]
Thanks for the contribution.

**Comment by webfolderio** [comment]
Hi @paine1690 

I compare the screenshots before and after the merge and see that result is different. First image after the merge and the second is before the merge. They should be same. Did you get similar result?

I tested on Windows platform.

new
old

**Comment by paine1690** [comment]
Hi @webfolderio 
Sorry I did not save the image before merge. And after the Chrome Devtools Protocol  API changed, it just throw an Exception. So I changed the code according to the new API. 

I  tested on Windows platform too, and my screenshots after the merge is same as yours before the merge.

test

So have you change any other information like userAgent?

**Comment by webfolderio** [comment]
> So have you change any other information like userAgent?
No, i did not change the UserAgent

What is your Chrome version?
Mine is: Version 59.0.3071.115 (Official Build) (64-bit) on Windows platform.

**Comment by paine1690** [comment]
@webfolderio 
版本 61.0.3159.0（正式版本）canary （64 位）

**Comment by webfolderio** [comment]
I installed and test with 61, it works. Thanks @paine1690

**Pull request merged**
