### PR TITLE
better treatment for the memory leak

### PR DESCRIPTION
**Pull request by inponomarev**
I experimented with your library and experienced out-of-heap/gc errors.  I analyzed heap dumps and found out that you didn't remove records from the contextList map. By coincidence you fixed this just today (and btw this is not 'minor' leak, if you run the library for several hours, this will drain your heap). I would like to propose more concise and reliable fix.

### CODE REVIEW

**Comment by webfolderio** [comment]
Thanks for the contribution.

> btw this is not 'minor' leak

It depends, contextList cleared when session is closed. If you have lots of long-lived sessions this memory leak might crash the JVM.

Version 2.1.4 is released.

**Comment by inponomarev** [comment]
Thanks for new versions on Maven Central!

> If you have lots of long-lived sessions this memory leak might crash the JVM.

This is exactly what I try to do. Now the leak is gone, but sessions die after some time. I see there is 'isConnected' property to help me. But maybe I'm doing things wrong: if I want to use Chrome browser as a server for my constantly running application, which strategy is better: to create/close short-lived sessions or to keep sessions in a pool?

**Comment by webfolderio** [comment]
I mostly create short-live session and never test long-live sessions.

WebSocket support ping feature `WebSocket.sendPing`. You might try to use `WebSocket.setPingInterval` to send periodical ping.

**Comment by nikhil-bidgely** [comment]
@inponomarev @webfolderio Creating Launcher, SessionFactory and Session and then closing these and calling launcher.kill() is taking a lot of time. I want to reuse the sessions to save time. I'm using a resource pool of sessions. I've used 2 strategies, please suggest which one is better:
1. Created a pool of resources (which consists of Launcher, SessionFactory & Session) by launching chrome on different ports and renewing all of these by closing and killing them all and re-initializing at regular periods. This is performing really well but I've a doubt that using same session and not closing it could leave me with the previous navigated page and I could again get previous pdf and not the pdf of the latest navigated url.
2. Getting new session every time & closing it after each use. This might solve the above problem but now I think session.close() also closes SessionFactory and factory.create(factory.createBrowserContext()) will fail.

@webfolderio I'd like to have a small hangout session for my use cases, please let me know if possible.

**Comment by inponomarev** [comment]
@nikhil-bidgely @webfolderio If possible, I also would like to participate.  In fact, at the moment I gave up the idea of using cdp4j because of its unstable work with long sessions/pools/multithreading. 

@nikhil-bidgely: I tried the 'session pool' strategy, be ready to 100% CPU / RAM utilization after a couple of hours.

And it seems to me there are also race conditions in the library (from time to time in multi-threaded environment I recieve error 'no frame with given Id found' from Chrome, which might be the sign that cdp4j gives Chrome the id from from wrong session). 

BUT, I have a very specific use case (I need to monitor many pages for a long period of time). In tests that run the library for a short periods of time everything is just perfect!

**Comment by nikhil-bidgely** [comment]
@inponomarev Chrome buffer fills after long usages, so you should close session and kill the launcher then use it again. I used this strategy by killing and re-initializing after couple of minutes/depending on number of usages of a session. My use case also requires me to run it continuously and process a lot of urls in a multi-threaded environment.

**Comment by inponomarev** [comment]
@nikhil-bidgely Hmmm... 'Chrome buffer fills after long usages' -- does this mean that the problem is in Chrome itself? At the moment, our system works with PhantomJS + self-made bridge to Java. There are lots of problems with PhantomJS, but it works somehow. What we do is forcibly killing PhantomJS after 40 minutes of usage. I looked for more stable solution with Chrome, but after a couple of weeks of trying I can see that our PhantomJS system simply works better than Chrome system! Going to try Firefox/Marionette now.

**Pull request merged**
