### PR TITLE
Update LinuxProcessManager.java to get pid from CDPProcess.Process

### PR DESCRIPTION
**Pull request by nikhil-bidgely**
Bug fix to get pid from CDPProcess.process

### CODE REVIEW

**Comment by webfolderio** [comment]
Thanks for the pull request.

**Comment by nikhil-bidgely** [comment]
@webfolderio due to this bug chrome process is not getting killed, as pid was not getting correctly assigned. Can we've a new release with this bug fix?

**Comment by webfolderio** [comment]
Version 2.1.2 is released.

**Comment by nikhil-bidgely** [comment]
@webfolderio We've been using cdp4j for a year now without any issues (release 2.1.0). But recently we've observed that chrome processes sometimes don't get closed and processing stops completely because of multiple chrome instances in the launched/stuck state. This is when we call io.webfolder.cdp.ProcessManager.kill() by Launcher.getProcessManager().kill()  it's returning false sometimes.
Nothing has changed we didn't update chrome/OS still we're facing this issue, could you tell us what could be the reason. I can share more details if needed.

**Comment by webfolderio** [comment]
Hi @nikhil-bidgely what is your operating system and Java version?

**Comment by nikhil-bidgely** [comment]
@webfolderio We're using 1.8.0_131 java version and we've been using Ubuntu 14.04.5 LTS OS. Yesterday, we just restarted the process and this issue almost is gone now but this is a major issue and we want to completely avoid it.

**Pull request merged**
